### ISSUE TITLE
When execute ChainerWing.py, occured AttributeError

### ISSUE THREAD

**Issue by MisooKim** [fukatani/ChainerWing#1]
Thank you for great GUI tool for Deep learning.
But I have some problem to execute ChainerWing.

`C:\Users\rose\ChainerWing\bin>python ChainerWing.py
Traceback (most recent call last):
  File "ChainerWing.py", line 4, in <module>
    chainer_wing.gui_main.main.run()
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\main.py", line 26, in run
    startUI(app, painter)
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\main.py", line 36, in startUI
    win = MainWindow(painter=painter)
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\painter.py", line 746, in __init__
    self.setupNodeLib()
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\painter.py", line 1111, in setupNodeLib
    self.NodeListView.setup(self.FilterEdit, self.drawer.graph)
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\node_lib.py", line 105, in setup
    self.filter.register_list_view(self)
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\node_lib.py", line 71, in register_list_view
    self.update_node_list(text)
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\node_lib.py", line 60, in update_node_list
    item.setToolTip(NODECLASSES[node].doc())
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\node.py", line 331, in doc
    return cls.register_chainer_impl().__doc__
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\CustomNodes\LinkNodes.py", line 21, in register_chainer_impl
    return chainer.links.linear
AttributeError: module 'chainer.links' has no attribute 'linear'`

I cannot find what is the faulty line in python files..

Would you notify how can i solve it?

**Comment by fukatani** [comment]
Thank you for trying ChainerWing!

It is ChainerWing bug, it supported chainer 2.0.0b1, but does not chainer 2.0.0 (stable).
I fixed it, could you try again?

**Comment by MisooKim** [comment]
Thank you to solve it.
A error doens't be occured~! Thankyou :-)
