### ISSUE TITLE
FileNotFoundError in my desktop

### ISSUE THREAD

**Issue by MisooKim** [fukatani/ChainerWing#2]
Steps to reproduce:

1. I follow the ChainerWing example.
2. Load the "mnist.json"
3. Click the Run
4. Stack trace occurred as bellow.

Observed Behavior:
```
`Traceback (most recent call last):

  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\painter.py", line 1056, in compile_and_exe
    if self.compile_runner():

  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\painter.py", line 1053, in compile_runner
    return self.drawer.graph.compile()

  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\graph.py", line 267, in compile
    result = compiler.Compiler()(self.nodes)

  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\compiler.py", line 22, in __call__
    net_file = open(TrainParamServer().get_net_name(), 'w')

FileNotFoundError: [Errno 2] No such file or directory: '/home/ryo/workspace/github/CW_gui/examples/mnist/MyNet.py'`
```

Solution:
I modify some specific(absolute) path of your computer in two files.
First file

> : ChainerWing\examples\mnist\mynet.py
Line 70, 74, 79, 87, 93

> : ChainerWing\examples\mnist\mnist.json
Line 236, 237, 243, 245

I would like to reflect the user's computer path in this line.
Thank you.

**Comment by fukatani** [comment]
Thank you for your report.
I changed default working directory and tutorial document.
Actually, user have to set data file and working directory (where net python file generated) correctly.

It is necessary to indicate the existing directory.
