### ISSUE TITLE
Feature Request for NO CUDA users

### ISSUE THREAD

**Issue by MisooKim** [fukatani/ChainerWing#3]
I don't use CUDA and cupy package.
ChainerWing also notice that cupy is optional.

However, to execute ChainerWing, It should be called the CUDA and cupy as bellow.

```
`Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\painter.py", line 1048, in exe_runner
    self.drawer.graph.run()

  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\gui_main\graph.py", line 288, in run
    self.runner.run()

  File "C:\Python\Python35\lib\site-packages\chainer_wing-0.0.0-py3.5.egg\chainer_wing\runner.py", line 23, in run
    cw_postprocess)

  File "C:/Users/rose/ChainerWing/examples/mnist//MyNet.py", line 61, in training_main
    device=0)
  File "C:\Python\Python35\lib\site-packages\chainer\training\updater.py", line 131, in __init__
    optimizer.target.to_gpu(device)

  File "C:\Python\Python35\lib\site-packages\chainer\link.py", line 726, in to_gpu
    with cuda._get_device(device):

  File "C:\Python\Python35\lib\site-packages\chainer\cuda.py", line 217, in _get_device
    check_cuda_available()

  File "C:\Python\Python35\lib\site-packages\chainer\cuda.py", line 79, in check_cuda_available
    raise RuntimeError(msg)

RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).No module named 'cupy'`
```

It is just optional feature request.
Would you add some function to turn on or turn off of GPU option?

**Comment by fukatani** [comment]
Could you try open train configuration and set GPU '0'?

**Comment by fukatani** [comment]
But we have to display message if cupy is not found instead of abnormal exit.
Thank you for your report.

**Comment by MisooKim** [comment]
Thank you. i solved it to set GPU '0'.
just my mistake.
Thank you
